_BASE_: "./CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  BACKBONE:
    NAME: "build_clip_resnet_backbone_from_pretrain"
  ROI_HEADS:
    NUM_CLASSES: 65
    NMS_THRESH_TEST: 0.5
  CLIP:
    NO_BOX_DELTA: True  # no box refinement
    OFFLINE_RPN_NMS_THRESH: 0.9