_BASE_: "../CLIP_fast_rcnn_R_50_C4.yaml"
MODEL:
  META_ARCHITECTURE: "MyCLIPFastRCNN"
  # IGNORE_CLS_LOSS: True
  CLIP:
    FREEZE_BACKBONE: True
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 5000
  CHECKPOINT_PERIOD: 10000
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
  EVAL_PERIOD: 20000