_BASE_: "../CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  META_ARCHITECTURE: "MyCLIPFastRCNN"
  ROI_HEADS:
    NUM_CLASSES: 65 # base + novel categories
  OVD:
    WITH_PSEUDO_LABELS: False   # no online PLs
    # box reg
    BOX_CONFIDENCE_THRES: 1.0   # no box reg for PL boxes
DATASETS:
  TRAIN: ("",)
  TEST: ("coco_2017_ovd_all_test",)
SOLVER:
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 5000